### ISSUE TITLE
Force Packages to be created with compact manifests.

### ISSUE THREAD

**Issue by njgheorghita** [ethpm/py-ethpm#71]
### What was wrong?
Valid manifests must be packed according to specific rules. 
```
The document must be tightly packed, meaning no linebreaks or extra whitespace.
The keys in all objects must be sorted alphabetically.
Duplicate keys in the same object are invalid.
The document must use UTF-8 encoding.
The document must not have a trailing newline.
```
We need to enforce that manifests used to instantiate packages follow these rules

### How can it be fixed?

Fill this section in if you know how this could or should be fixed.

**Comment by pipermerriam** [comment]
Implementation will look something like the following

- load the raw manifest
- parse the raw manifest
- dump the manifest using the proper config in `json.dumps` to dump with sorted keys and no extra whitespace.
- verify that the dumped manifest exactly matches the raw manifest.

**Comment by mkosowsk** [comment]
Hi @pipermerriam, do you feel this issue is worth a bounty and if so, how much? I am disbursing funds for the ECF Web 3.0 Infrastructure Fund and would love to compensate @njgheorghita for his time and hard work 👍 

Using DAI and currently targeting $120/dev hour or ~$350/for the average issue as a level set for pricing :)

@gnidan if you get a moment, please use [Gitcoin requests](https://gitcoin.co/requests) to tag issues for bounties with an amount that you find appropriate. It should take <30 seconds per issue and makes it easy for bookkeeping on my end. This should be able to get some fresh eyes from the Gitcoin bounty hunter community on the repo 👍 

Thanks!

**Comment by pipermerriam** [comment]
@mkosowsk maybe, but I think there are higher priority issues in other repos that would be more appropriate (nick works with me for the EF so he's been/being compensated for this work).  Can we work on creating/aggregating some issues for you to bounty?  What's the best way for us to communicate those to you.

**Comment by mkosowsk** [comment]
@pipermerriam cool!

I am keeping a sharp eye on [Gitcoin requests](https://gitcoin.co/requests), so once you have those issues created/aggregated if you could run them through the that quick Request process I will have them funded in <24 hrs (except weekends!). 👍

**Comment by cburgdorf** [comment]
@mkosowsk I submitted one for https://github.com/ethereum/py-evm/issues/1398 That one should be paid out in milestones as the task is a bit bigger. I mentioned that in the comment section. (Sorry for hijacking this issue)

**Comment by mkosowsk** [comment]
Thanks @cburgdorf, I will process with the Gitcoin team and get back to you :)
